### ISSUE TITLE
Clean UP & Dockerization eos1579

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos1579#1]

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron 
I start this model by testing it with` run_predict.sh `and then with `repo_path` without doing any changes in it except the change of `RDkit` in dockerfile, because dockerfile uses the same RDkit version that requires conda-forge for installation  as two of my previous model did and this version doesn't install with conda-forge as it freezes during installation. So i used the solution i did in previous two models to install RDkit with pip-pypi.  Secondly, it was initially throwing me an error `ModuleNotFoundError: No module named 'pandas'` so i did mention it in dockerfile like this `RUN pip install pandas` and nothing else, did no refactoring at all

It is working fine and giving me output perfectly when running it with `run_predict.sh` and giving me output too, here's the ouput file [eos15709_ Output.csv](https://github.com/ersilia-os/eos1579/files/12030158/eos15709_.Output.csv)
But when i tries to fetch it with `--repo-path` it is executing normally, creating conda env for model too and install packages as well but something then went wrong after that and it gives me 

```
🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

Cannot choose from an empty sequence 
```
Here's the complete error log 

[eos1579_log.log](https://github.com/ersilia-os/eos1579/files/12030175/eos1579_log.log)

I just couldn't understand the error. which sequence or data is it pointing to, it seems like it is giving that error while loading data and couldn't find it. 
Thanks

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron @DhanshreeA 
Here's the updated Dockerfile


[Dockerfile.txt](https://github.com/ersilia-os/eos1579/files/12038461/Dockerfile.txt)

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya 
Sorry I haven't had time to look at this model in detail. Let me check !

**Comment by DhanshreeA** [comment]
Thanks @ZakiaYahya looking into this.

**Comment by DhanshreeA** [comment]
I can definitely reproduce this error @ZakiaYahya looking into it more now.

**Comment by GemmaTuron** [comment]
@ZakiaYahya and @DhanshreeA I am on my MacOS today, I prefer to run the debugging on Linux so I'll be able to check this tomorrow !

**Comment by DhanshreeA** [comment]
Hey @ZakiaYahya @GemmaTuron I looked into this a bit yesterday. This model returns a list of floats, and the output csv is being serialized from a pandas dataframe. My initial hypothesis was that Ersilia CLI doesn't process list outputs when they are indeed comma separated values (ie across more than one column), so I tried making it so that the output csv puts a list of values in a single column only. However it turns out that's not the case either. The BentoML service is returning empty outputs all the time even when you query the server directly. If I understood correctly from the lab meeting yesterday, something similar happened with one of the models @samuelmaina was working on. I'll try to look more into this today. In the meantime, @ZakiaYahya can you also put print statements in the service.py file and try to figure out what's happening?

**Comment by GemmaTuron** [comment]
@DhanshreeA 

Thanks for the help! I will look into it this afternoon as well

**Comment by ZakiaYahya** [comment]
Hello @DhanshreeA 
Thanks for the detail, Yeh sure let me try that.
Thanks

**Comment by GemmaTuron** [comment]
@ZakiaYahya 

I can also reproduce this, what I see is that there is a conflict with protobuf when fetching from Ersilia which might be causing this error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bentoml 0.11.0 requires protobuf<3.19,>=3.8.0, but you have protobuf 3.19.6 which is incompatible.
```

Indeed is an issue between tensorflow and protobuf. I've tried bumping the py version to 3.10 or 3.8 to see if this would immmediately solve the issue but it looks like we will need some more work.
We need to find a version of tf that works with the rest oft he packages. I see they [pin](https://github.com/the-ahuja-lab/Metabokiller/tree/main) the signaturizer to v1.1.11 and scikit learn to 1.0.2, maybe we could try these as well!
Hope this is helpful!
```
Detailed error:
Model API eos1579:predict did not produce an output2023-07-16 10:40:37.117838: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/gturon/eos/repository/eos1579/20230716103943_8D360E/eos1579/artifacts/framework/code/main.py", line 5, in <module>
    from Metabokiller import mk_predictor as mk
  File "/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/Metabokiller/mk_predictor.py", line 1, in <module>
    from signaturizer import Signaturizer
  File "/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/signaturizer/__init__.py", line 1, in <module>
    from .signaturizer import Signaturizer, SignaturizerResult
  File "/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/signaturizer/signaturizer.py", line 7, in <module>
    import tensorflow as tf
  File "/hom
```e/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/tensorflow/core/framework/function_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/google/protobuf/internal/__init__.py)

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron 
Thanks for the detail explanation. I'll try to test it with different version of tensorflow and will let you know. Can you kindly let me know which log file you're looking at, as session/current log files didn't tell any about this error. Are you looking at some ersilia temporary files that contain all this information??
Thanks

**Comment by GemmaTuron** [comment]
@ZakiaYahya 
I also see the TF error in the log you shared. Look at it again please:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-hub 0.13.0 requires protobuf>=3.19.6, but you have protobuf 3.18.3 which is incompatible.
Successfully installed protobuf-3.18.3
```

**Comment by ZakiaYahya** [comment]
Right @GemmaTuron 
But before that error it is also giving error
 
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bentoml 0.11.0 requires protobuf<3.19,>=3.8.0, but you have protobuf 3.19.6 which is incompatible.` 

And i'm little bit confused in both errors, in this error it requires protobuf<3.19, >=3.8.0 but the installed version is `protobuf 3.19.6` and in tensorflow-hub error it says that the installed `probtobuf is 3.18.3`, why it is showing two different version of protobuf installed? 

The required protobuf version that is compatible with bentoML is not compatible with tensorflow-hub and the other version of protobuf that is compatible with tensorflow-hub is not compatible with bentoML.

Bentoml     requires protobuf  >=3.8 & <3.19  but the installed protobuf is 3.19.6
Tensorflow requires protobuf  >=3.19.6  but the installed protobuf is 3.18.3

**Comment by GemmaTuron** [comment]
yes, usually Ersilia deals with the bentoML protobuf issues, which is why it fixes the version to 3.18. @miquelduranfrigola can share more on this!
Which versions would TF Hub need?

**Comment by samuelmaina** [comment]
> @ZakiaYahya
> 
> I can also reproduce this, what I see is that there is a conflict with protobuf when fetching from Ersilia which might be causing this error:
> 
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> bentoml 0.11.0 requires protobuf<3.19,>=3.8.0, but you have protobuf 3.19.6 which is incompatible.
> ```
> 
> Indeed is an issue between tensorflow and protobuf. I've tried bumping the py version to 3.10 or 3.8 to see if this would immmediately solve the issue but it looks like we will need some more work. We need to find a version of tf that works with the rest oft he packages. I see they [pin](https://github.com/the-ahuja-lab/Metabokiller/tree/main) the signaturizer to v1.1.11 and scikit learn to 1.0.2, maybe we could try these as well! Hope this is helpful!
> 
> ```
> Detailed error:
> Model API eos1579:predict did not produce an output2023-07-16 10:40:37.117838: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> Traceback (most recent call last):
>   File "/home/gturon/eos/repository/eos1579/20230716103943_8D360E/eos1579/artifacts/framework/code/main.py", line 5, in <module>
>     from Metabokiller import mk_predictor as mk
>   File "/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/Metabokiller/mk_predictor.py", line 1, in <module>
>     from signaturizer import Signaturizer
>   File "/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/signaturizer/__init__.py", line 1, in <module>
>     from .signaturizer import Signaturizer, SignaturizerResult
>   File "/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/signaturizer/signaturizer.py", line 7, in <module>
>     import tensorflow as tf
>   File "/hom
> ```e/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/tensorflow/__init__.py", line 38, in <module>
>     from tensorflow.python.tools import module_util as _module_util
>   File "/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 37, in <module>
>     from tensorflow.python.eager import context
>   File "/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
>     from tensorflow.core.framework import function_pb2
>   File "/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/tensorflow/core/framework/function_pb2.py", line 5, in <module>
>     from google.protobuf.internal import builder as _builder
> ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/home/gturon/anaconda3/envs/eos1579/lib/python3.8/site-packages/google/protobuf/internal/__init__.py)
> ```

Hi @ZakiaYahya,
 I have just encounters this today. The same exact error.For my case I wasn't sure which package was using a higher `protobuf`.  I used gitlens to look at the last commits on the docker file and then added the latest package version by the commit date for all packages.This resolved the issue.Its not a must you use git lense you can read the last commits by a person on GitHub

**Comment by ZakiaYahya** [comment]
Hello @samuelmaina 
Thanks for the suggestion, yes i'm exactly trying the same thing. Let's see.
Thanks.

**Comment by ZakiaYahya** [comment]
Hi @GemmaTuron @DhanshreeA 
I've used `signaturizer version 1.1.11` as specified in the original repo https://github.com/the-ahuja-lab/Metabokiller/tree/main , plus i've used the latest available version `signaturizer==1.1.13` but still got the same error, As `tensorflow-hub` is installing along with the signaturizer package and not as a separate package but still i tried doing `RUN pip install --upgrade tensorflow-hub` as well and even tries to `install pip install tensorflow-protobuf` to resolve tensorflow and protobuf dependancy clashes but nothing works to resolve this error.
Any suggestion?

**Comment by DhanshreeA** [comment]
Hi @GemmaTuron @samuelmaina 

While I agree that the protobuf dependency conflict is indeed present in this model, however that is **not** what is causing issues here. If that was indeed the case, then I would not have been able to run the main.py file on any SMILE string. 

The problem indeed was with service.py file as I had previously explained to @ZakiaYahya and in my comments above. Modifying that file, **I have been able to successfully fetch the model**. (See attached logs)
[eos1579.log](https://github.com/ersilia-os/eos1579/files/12077130/eos1579.log)

I'll explain this step by step:

```python
_result_df = EnsembleMK.predict(canonical_smiles_list)
```
The EnsembleMK API returns a dataframe (and not a list), while I haven't examined what is in the dataframe exactly, it appears that the first column is not a Float.

When `service.py` file tries to process this output for the BentoML server to return it as a JSON, it does the following:
```python
            for r in reader:
                print([{"outcome": [Float(x) for x in r]}])
                R += [{"outcome": [Float(x) for x in r]}][1:]
```
Now the list[dict] looks something like: `[{outcome: [None, float, float, ...]}]`. I think the intention with the list slicing was to get rid of the first None value however that slice is applied to the wrong list. An interesting thing with Python lists is that if you try to slice the list with the index that cannot exist in the list, it will give you an empty list instead of an `IndexError` error. (This is possibly because Lists are mutable objects!) Eg:

```python
>>> a=[1,2,3]
>>> a[3:]
[]
```
If I move the slice to the inner list, the model works just fine.

**Comment by DhanshreeA** [comment]
@ZakiaYahya let me know if the comment above makes sense, and please modify the service.py file accordingly and test it out. :)

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron @DhanshreeA 
I've somehow resolve the clash that occurs between Tensorflow-Hub and protobuf by downgrading the TF manually in dockerfile from 0.14.0 to 0.12.0. But the clash between bentoML and protobuf still residing. 
I have two queries here:

(1) Protobuf is changing a lot while fetching from` 3.18.3 -> 3.17.3 -> 3.19.6 -> 3.18.3 -> 3.19.6 -> 3.18.3.` which is not under over control at all.

(2) Can we change bentoML version from 0.11.0 to other because in first line of dockerfile it is mentioned as 
    `FROM bentoml/model-server:0.11.0-py37`

**Comment by ZakiaYahya** [comment]
Hello @DhanshreeA 
Thanks for pointing it out, Let me check it as well. I shifted working on versions instead of working on service.py as Samuel and Hellen also getting the same error while fetching and they fix it by using the appropriate versions of packages that are compatible with protobuf and other packages as well and Gemma also point out the problem in packages. But what you're saying is making sense as well. Let me test it and redo changes in Dockerfile as i did changes in it to fix the problem.
Thnaks for the help :)

**Comment by DhanshreeA** [comment]
I do agree with everyone here @ZakiaYahya , it is always a good practice to specify exact versions of dependencies because just doing a `pip install xyz` will always install the latest version which may not be compatible with everything else. A general practice is to take the state of your current environment if there are no conflicts and the code is working, and just pin those versions in the Dockerfile.

**Comment by samuelmaina** [comment]
> Hi @GemmaTuron @samuelmaina
> 
> While I agree that the protobuf dependency conflict is indeed present in this model, however that is **not** what is causing issues here. If that was indeed the case, then I would not have been able to run the main.py file on any SMILE string.
> 
> The problem indeed was with service.py file as I had previously explained to @ZakiaYahya and in my comments above. Modifying that file, **I have been able to successfully fetch the model**. (See attached logs) [eos1579.log](https://github.com/ersilia-os/eos1579/files/12077130/eos1579.log)
> 
> I'll explain this step by step:
> 
> ```python
> _result_df = EnsembleMK.predict(canonical_smiles_list)
> ```
> 
> The EnsembleMK API returns a dataframe (and not a list), while I haven't examined what is in the dataframe exactly, it appears that the first column is not a Float.
> 
> When `service.py` file tries to process this output for the BentoML server to return it as a JSON, it does the following:
> 
> ```python
>             for r in reader:
>                 print([{"outcome": [Float(x) for x in r]}])
>                 R += [{"outcome": [Float(x) for x in r]}][1:]
> ```
> 
> Now the inner list[dict] looks something like: `[{outcome: [None, float, float, ...]}]`. I think the intention with the list slicing was to get rid of the first None value however that slice is applied to the wrong list. An interesting thing with Python lists is that if you try to slice the list with the index that cannot exist in the list, it will give you an empty list instead of an `IndexError` error. (This is possibly because Lists are mutable objects!) Eg:
> 
> ```python
> >>> a=[1,2,3]
> >>> a[3:]
> []
> ```
> 
> If I move the slice to the inner list, the model works just fine.

Thanks @DhanshreeA for providing the insight,totally makes sense for parsing of the output.

**Comment by samuelmaina** [comment]
@ZakiaYahya , I will try running the model.Its strange that @DhanshreeA does get package errors while you get them.

**Comment by DhanshreeA** [comment]
> @ZakiaYahya , I will try running the model.Its strange that @DhanshreeA does get package errors while you get them.

@samuelmaina I think you meant I don't get package errors? In fact, I do, I see the error for the same version conflict with protobuf. But even with the conflicting version the code in main.py is still running just fine. Please do note I'm not advocating for keeping problematic dependencies here, I'm just pointing out that it's not the culprit behind why this model isn't running with ersilia.

**Comment by samuelmaina** [comment]
> > @ZakiaYahya , I will try running the model.Its strange that @DhanshreeA does get package errors while you get them.
> 
> @samuelmaina I think you meant I don't get package errors? In fact, I do, I see the error for the same version conflict with protobuf. But even with the conflicting version the code in main.py is still running just fine. Please do note I'm not advocating for keeping problematic dependencies here, I'm just pointing out that it's not the culprit behind why this model isn't running with ersilia.

I get you now @DhanshreeA .Running main.py in the run.sh will avoid the bentoml conflict.

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron @DhanshreeA @samuelmaina 
Yes the main problem behind the issue is not the protobuf issue , it's actually in the service.py as @DhanshreeA pointed. I've did the changes in the service.py to apply slicing on inner list which is returning the float values, instead of outer list which is empty that's why it keep throwing an error `"Cannot choose from an empty sequence" `. Now, the model fetch, serve and predict successfully. Working on refactoring the model now. Once it done, i'll open the PR.
Thanks

**Comment by GemmaTuron** [comment]
Great job @DhanshreeA and @ZakiaYahya 
Really appreciate the effort in this!

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron @DhanshreeA 
Changes i've done in this model
Model is not working initially before refactoring because of two things
(1) Dockerfile
(2) Service.py

In **Dockerfile**, the mentioned RDkit version is `conda install -c conda-forge rdkit=2021.03.4` which freezes during installation, So what i did i changed the RDkit version to` pip install rdkit-pypi==2022.3.1b1`. Secondly it is giving an error `ModuleNotFoundError: No module named 'pandas'` So to resolve this, i added `RUN pip install pandas` in the Dockerfile.

**Service.py**: Model is working fine with above Dockerfile with run.sh but it is giving an error `"Cannot choose from an empty sequence"` when run it with `--repo-path`, it seems like the problem resides with `service.py` or `bentoML` as the model is working fine with `run.sh`. So, when dig into the details it comes out the problem is in `service.py`, when processing the data the slicing is applied to wrong list that is the empty list and that's why service.py eventually returns an error `Cannot choose from an empty sequence`. Applying the slicing to correct list eventually makes the model works both with run.sh and with --repo-path.
Changes are from this

```
            for r in reader:
                R += [{"outcome": [Float(x) for x in r]}][1:]
```
to this

```
            for r in reader:
                R += [{"outcome": [Float(x) for x in r][1:]}]
```
Moving the slicing to inner list, instead of outer list.

For Refactoring Purpose: I've done following changes
(1) Deleted all `.dvc` folders and files
(2) Modify `service.py` from predict api to run api
(3) Update` LICENSE` file
(4) Rename `run_predict.sh` to run.sh

**Comment by ZakiaYahya** [comment]
Changes i've done in this model
Model is not working initially before refactoring because of two things
(1) Dockerfile
(2) Service.py

In Dockerfile, the mentioned RDkit version is conda install -c conda-forge rdkit=2021.03.4 which freezes during installation, So what i did i changed the RDkit version to pip install rdkit-pypi==2022.3.1b1. Secondly it is giving an error ModuleNotFoundError: No module named 'pandas' So to resolve this, i added RUN pip install pandas in the Dockerfile.

Service.py: Model is working fine with above Dockerfile with run.sh but it is giving an error "Cannot choose from an empty sequence" when run it with --repo-path, it seems like the problem resides with service.py or bentoML as the model is working fine with run.sh. So, when dig into the details it comes out the problem is in service.py, when processing the data the slicing is applied to wrong list that is the empty list and that's why service.py eventually returns an error Cannot choose from an empty sequence. Applying the slicing to correct list eventually makes the model works both with run.sh and with --repo-path.
Changes are from this

            for r in reader:
                R += [{"outcome": [Float(x) for x in r]}][1:]
to this

            for r in reader:
                R += [{"outcome": [Float(x) for x in r][1:]}]
Moving the slicing to inner list, instead of outer list.

For Refactoring Purpose: I've done following changes
(1) Deleted all .dvc folders and files
(2) Modify service.py from predict api to run api
(3) Update LICENSE file
(4) Rename run_predict.sh to run.sh

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron @DhanshreeA 
I've open PR on the model, Kindly check it.
Thanks

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron @DhanshreeA 
The model is failing at `"Upload to DockerHub"`, and it is not failing at ARM64/AMD64 builds , it is surprisingly failing at `"Ersilia Installation"`. It is showing following errors
```
Python recognizes 'ersilia.hub.content.metadata' as an importable package[^1],
but it is absent from setuptools' `packages` configuration.
```
```
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed cleaning build dir for ersilia
Failed to build ersilia
```
```
ERROR: Could not build wheels for ersilia, which is required to install pyproject.toml-based projects
Error: Process completed with exit code 1.
```
You can view full log here
[eos1579_log.txt](https://github.com/ersilia-os/eos1579/files/12091342/eos1579_log.txt)

In my undestanding the problem isn't lies in model code, it's basically not installing `ersilia setup` when reach at these steps of `github/workflows/upload-model-to-dockerhub.yml` line 124

```
      - name: Install ersilia
        run: |
          source activate
          python --version
          echo "After conda init"
          conda init
          python -m pip install git+https://github.com/ersilia-os/ersilia.git
```
@GemmaTuron any idea why this is happening?

**Comment by GemmaTuron** [comment]
@ZakiaYahya 
Sorry Airtable seemed to be down for a few hours. I've rerun the workflows

**Comment by ZakiaYahya** [comment]
Alright @GemmaTuron 
I'm checking the workflows.
Thanks.

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron 
The model successfully uploaded to DockerHub.
Thanks
